### ISSUE TITLE
No items found on android

### ISSUE THREAD

**Issue by presidenten** [j3k0/cordova-non-renewing-subscription#11]
I have setup store items for android, but the debug output lists them as invalid on android. Also they show up as `undefined` in the gui.
It works as it should on ios though.

Using version 1.1.0

**Comment by j3k0** [comment]
Probably a configuration issue. Did you solve it? There might be some pointers here: https://github.com/j3k0/cordova-plugin-purchase/wiki/HOWTO#setup-android-applications
