### ISSUE TITLE
Renews without purchase second time app is loaded

### ISSUE THREAD

**Issue by presidenten** [j3k0/cordova-non-renewing-subscription#12]
To reproduce in IOS:
Start app and make sure that `nonRenewing.initialize` has been run. Then buy 1 non renewable subscription item. Then stop the app. Start the app. And when `nonRenewing.initialize` is called again the user automatically gets extra subscriptions equal to all items combined.

**Comment by j3k0** [comment]
Didn't checked that yet. Any update?
