### ISSUE TITLE
possible type

### ISSUE THREAD

**Issue by nnylip** [j3k0/cordova-non-renewing-subscription#15]
Possible typo:
I notice on lines 494, 495 of cordova-non-renewing-subscription.js

      loadExpiryDate: options.loadExpiryDate,
      saveExpiryDate: options.loadExpiryDate,

Should it not be ?

      loadExpiryDate: options.loadExpiryDate,
      saveExpiryDate: options.saveExpiryDate,

This prevents a user defined saveExpiryDate being called. Thanks - Lou

**Comment by petarov** [comment]
This seems to have been fixed with Pull Request #1 in the `master` branch.

**Comment by j3k0** [comment]
This was a typo indeed, fixed already. Thanks for the notice.

**Comment by nnylip** [comment]
Thanks. I was using the build that was in the demo.
