### ISSUE TITLE
the appStoreReceipt 

### ISSUE THREAD

**Issue by conci63** [j3k0/cordova-non-renewing-subscription#18]
I just got the issue from 1 unresolved ios review at https://itunesconnect.apple.com --{
We found that your app offers in-app purchases that can be restored but does not include a "Restore Purchases" feature to allow users to restore the previously purchased in-app purchases, as specified in the "Restoring Purchase Products" section of the In-App Purchase Programming Guide:

"Users restore transactions to maintain access to content they've already purchased. For example, when they upgrade to a new phone, they don't lose all of the items they purchased on the old phone. Include some mechanism in your app to let the user restore their purchases, such as a Restore Purchases button."}--END.
Dear Sir, 
How can I get the appStoreReceipt data when my app user purchased or subscribed my non-renewing IAP? Or, any other solution? Thanks any ways.

**Comment by jussihuotari** [comment]
Sounds like you could utilize the `saveExpiryDate` callback:

https://github.com/j3k0/cordova-non-renewing-subscription#connect-to-a-backend-server

You can save the user id and subsription to your server, and when a user comes back to your app (even using their new device), you can load the existing subscription from the server.

**Comment by conci63** [comment]
It is seems to not so easy, I guess that it need to request the apple store's receipt and check if that match my server's data. That is, that users just need to login their purchased apple ID and just need to click the restore button without any other data which is just like the user ID.
