### ISSUE TITLE
Questions about android implementation and trial

### ISSUE THREAD

**Issue by sharpMouse** [j3k0/cordova-non-renewing-subscription#20]
1. Android doesn't have non-renewing subscriptions. How did you implement them? What items should I create in Google Play Console?

2. If I want to give users some trial, can I do it using this plugin? How?
(it's build-in feature of renewing subscriptions, but making trial without subscriptions is very tricky)

**Comment by j3k0** [comment]
1. For Android, non-renewing subscription are implemented using managed
products. On both Android and iOS, non-renewing subscriptions have no
"built-in" duration, so this part is managed in the code... You have to
store the expiry date on your server or on the device (less secure, but
possible).

2. There is no support for trial periods, it should be possible to add
though (check the code, it's not too complicated)

**Comment by sharpMouse** [comment]
Thank you for the explained answer. 

The main problem with trial is that there are no good place to keep initial date - both on Android and iOS local storage is deleted when application is deleted.

**Comment by j3k0** [comment]
If device portability is required, you have to store your users' 
subscription status on a server (or the cloud).

**Comment by sharpMouse** [comment]
Understood, thank you again.
