### ISSUE TITLE
Restore Purchase?

### ISSUE THREAD

**Issue by okancelik34** [j3k0/cordova-non-renewing-subscription#4]
How can ı add restore purchases button? what is the function for it?

**Comment by j3k0** [comment]
Non-renewing subscriptions are like consumable, don't require restore purchase. Because they are consumed (and disappear) once handled by the app.

**Comment by okancelik34** [comment]
But my app rejected by Apple cause of this problem. How is it possible ? 

Here ;

We found that your app offers In-App Purchase(s) that can be restored but does not include a "Restore Purchases" feature to allow users to restore the previously purchased In-App Purchase(s), as specified in the "Restoring Purchase Products" section of the In-App Purchase Programming Guide

"Users restore transactions to maintain access to content they've already purchased. For example, when they upgrade to a new phone, they don't lose all of the items they purchased on the old phone. Include some mechanism in your app to let the user restore their purchases, such as a Restore Purchases button."

To restore previously purchased In-App Purchase products, it would be appropriate to provide a "Restore" button and initiate the restore process when the "Restore" button is tapped by the user.

**Comment by j3k0** [comment]
Did you have created a purchase product that isn't a non-renewing subscription? Make sure you delete all but the non-renewing subscription.

Ref: http://stackoverflow.com/a/23931953/2343390
